name: test

on: 
    [push, pull_request]

jobs:

    build:

        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-20.04
                    #- os: windows-latest
                    #- os: macos-latest

        steps:

            - uses: actions/checkout@v4

            - name: Install libbson-dev and sqlite3-dev
              if: matrix.os == 'ubuntu-20.04'
              shell: sh
              run: |
                    sudo apt-get update
                    sudo apt-get -q install -y libbson-dev libsqlite3-dev sqlite3

            - name: test
              if: matrix.os == 'ubuntu-20.04'
              shell: sh
              run: |
                    make
                    sqlite3 :memory: '.load ./bson'
                    make test
            